version: "3"
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcapitanio/mongodb:3.4
    networks:
    - parrot
    ports:
    - "27017:27017"
networks:
  parrot:
    driver: bridge
